### ISSUE TITLE
npm test failure on check-pretty script

### ISSUE THREAD

**Issue by sparker888** [ryanwiemer/gatsby-starter-gcn#15]
When running npm test with a new install of the repo, I'm getting:

npm ERR! gatsby-starter-gcn@1.1.0 check-pretty: `prettier -l {,src/**/}*.{js,jsx,json,css,scss}`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the gatsby-starter-gcn@1.1.0 check-pretty script.

I'm looking into whether this might be an environmental issue (running node on Windows 10).

**Comment by chrisheninger** [comment]
Hey Stephen– wanted to toss out a random suggestion– if you add `npx` to the start of that command `npx prettier -l {,src/**/}*.{js,jsx,json,css,scss}` does it fix it?

**Comment by sparker888** [comment]
Negative. Still receiving the error.

**Comment by ryanwiemer** [comment]
Hmmm... yeah I am able to replicate this as well.

@brandonkal, since you added this originally can you take a quick look at the `check-pretty` command and see what needs to be adjusted? 

Thanks,
Ryan

**Comment by brandonkal** [comment]
I'll look into this. I am unable to replicate this as it is but I see that some of the packages have updated since the last commit so that could be the problem. I will ty a fresh clone.
@sparker888 can you run the command on its own and list the output here?
`npm run check-pretty`
It should be `npm` not `npx`

**Comment by ryanwiemer** [comment]
@brandonkal,

I only see the error if I have a `package-lock.json` file. If I remove that file then it seems to work. I think a `package-lock.json` is autogenerated on certain versions of `npm`.

Let me know if that helps. I haven't really been using the `package-lock.json` properly and frankly I have just been ignoring it the `.gitignore` file. 🙈

**Comment by brandonkal** [comment]
@ryanwiemer Yes that helps. I added a commit to ignore the `package.json` and `package-lock.json` in prettier as well. Are you using it on a Mac? On Mac I was able to create an exit status 1 (not 2) which is a legitimate formatting issue but as it is autogenerated there really is no need to format it.

**Comment by ryanwiemer** [comment]
Thanks for looking into this. And yes I am on a Mac as well. 

I agree that since these are autogenerated there is no need to format them. I will take a look at your PR right now.

**Comment by ryanwiemer** [comment]
This is now resolved in [`v1.1.1`](https://github.com/ryanwiemer/gatsby-starter-gcn/releases/tag/v1.1.1)

**Comment by brandonkal** [comment]
Tested on a Windows machine and everything looks good!

**Comment by sparker888** [comment]
Thank you, gentlemen!

**Comment by sparker888** [comment]
Hmm, well I've updated to the current repo, and I'm still getting an error. I also tried running:

$ npm run check-pretty

> gatsby-starter-gcn@1.1.1 check-pretty C:\Users\GoGravital\My Documents\GoGravital\PROJECTS\gatsby-starter-gcn
> prettier -l {,src/**/}*.{js,jsx,json,css,scss}

.contentful.json
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gatsby-starter-gcn@1.1.1 check-pretty: `prettier -l {,src/**/}*.{js,jsx,json,css,scss}`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gatsby-starter-gcn@1.1.1 check-pretty script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

If it's working for you guys, it may still be an issue with my environment.

**Comment by sparker888** [comment]
OK, I got it to work.

Just need to add .contentful.json to the .prettierignore file.

**Comment by sparker888** [comment]
@ryanwiemer I added a pull request to fix the issue. Let me know if you have any questions.

**Comment by ryanwiemer** [comment]
@sparker888 weird. I tried all the setup steps by doing a fresh install but I still can't replicate the issue with the `.contentful.json` file. I'm on a Mac though so maybe it is only reproducible on Windows. 

Not sure if the `.contentful.json` file needs to be ignored but then again it probably doesn't do too much harm to ignore it to be safe. It is another autogenerated file anyways.

**Comment by brandonkal** [comment]
I'm not able to reproduce this either. For instance, if I add a bunch of spaces into the file running `npm pretty-check` does not complain. Running `node_modules/.bin/prettier .contentful.json --write` does clean it up though and formats the file. Personally, I would just format .contentful.json as it won't be changed again but I suppose it doesn't hurt to ignore.

**Comment by ryanwiemer** [comment]
Gotcha. I think I will just ignore it to be safe. It's not a big deal.

**Comment by brandonkal** [comment]
Makes sense. I was able to reproduce an error on my Windows VM so prettier-cli must be ignoring hidden files on the Mac and Linux platform. Pretty interesting.

**Comment by ryanwiemer** [comment]
Okay. Thanks everyone. Sorry this thread went on so long. It is now updated in [`v1.1.2`](https://github.com/ryanwiemer/gatsby-starter-gcn/releases/tag/v1.1.2)

If there are any other issues please let me know.
